name = "Timer Hugo"
license = "CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Hugo port of the Themefisherâ€™s Navigator Template"
homepage = "https://gethugothemes.com/products/timer-hugo-theme/"
tags = ['landing-page', 'google-analytics', 'fast', 'light', 'white', 'modern', 'business', 'agency-template', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'company', 'projects', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages']
features = ['bootstrap','responsive']
min_version = "0.58.0"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com/"