name = "Timer Hugo"
license = "MIT"
licenselink = "https://github.com/themefisher/timer-hugo/blob/master/LICENSE"
description = "Hugo port of the Themefisherâ€™s Navigator Template"
homepage = "https://gethugothemes.com/products/timer-hugo-theme/"
tags = ['landing-page', 'google-analytics', 'fast', 'light', 'white', 'modern', 'business', 'agency-template', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'company', 'projects', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'gethugothemes']
features = ['bootstrap','responsive','fast']
min_version = "0.60.0"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com/"